// packages/react/src/breadcrumb/breadcrumb-link.tsx
import type { BreadcrumbLinkProps } from './breadcrumb.types';

/**
 * The current page stays a link to itself and carries aria-current="page",
 * which is what the Authoring Practices breadcrumb example does. Removing the
 * href would take the last crumb out of the tab order and out of the list a
 * screen reader reads as links.
 */
export function BreadcrumbLink({
  'aria-current': ariaCurrent,
  current = false,
  ...nativeProps
}: BreadcrumbLinkProps) {
  return (
    <a
      {...nativeProps}
      aria-current={ariaCurrent ?? (current ? 'page' : undefined)}
      data-current={current ? '' : undefined}
      data-part="link"
    />
  );
}

// packages/angular/breadcrumb/src/breadcrumb-link.ts
import { booleanAttribute, computed, Directive, ElementRef, inject, input } from '@angular/core';

/**
 * The current page stays a link to itself and carries aria-current="page",
 * which is what the Authoring Practices breadcrumb example does. Removing the
 * href would take the last crumb out of the tab order and out of the list a
 * screen reader reads as links.
 */
@Directive({
  selector: 'a[slBreadcrumbLink]',
  standalone: true,
  host: {
    'data-part': 'link',
    '[attr.aria-current]': 'ariaCurrent()',
    '[attr.data-current]': "current() ? '' : null",
  },
})
export class SlBreadcrumbLink {
  readonly current = input(false, { transform: booleanAttribute });

  private readonly ownAriaCurrent = inject(ElementRef<HTMLElement>).nativeElement.getAttribute(
    'aria-current',
  );

  readonly ariaCurrent = computed(() => this.ownAriaCurrent ?? (this.current() ? 'page' : null));
}
