// packages/react/src/breadcrumb/breadcrumb-list.tsx
import type { BreadcrumbListProps } from './breadcrumb.types';

/**
 * An ordered list, because the crumbs are a path and their order is the
 * information. A ul would say these are siblings.
 */
export function BreadcrumbList(props: BreadcrumbListProps) {
  return <ol {...props} data-part="list" />;
}

// packages/angular/breadcrumb/src/breadcrumb-list.ts
import { Directive } from '@angular/core';

/**
 * An ordered list, because the crumbs are a path and their order is the
 * information. A ul would say these are siblings.
 */
@Directive({
  selector: 'ol[slBreadcrumbList]',
  standalone: true,
  host: {
    'data-part': 'list',
  },
})
export class SlBreadcrumbList {}
