// packages/angular/input/src/input.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  ViewEncapsulation,
} from '@angular/core';
import { SlField } from '@slotted/angular/field';

export type InputSize = 'sm' | 'md' | 'lg';

/**
 * The native control, wired to the field around it when there is one and
 * standing alone when there is not.
 *
 * Every shared state is undefined by default. Unset defers to the field; set
 * wins over it, in both directions. The resolved value is mirrored onto the
 * element as a data attribute, so the stylesheet is one selector and an input
 * outside a field looks the same as one inside it.
 *
 * `SlField` is imported by its published path. A relative path into the field
 * entry point's source compiles each entry point its own copy of the class,
 * and two copies of a class are two injection tokens.
 */
@Component({
  selector: 'input[slInput]',
  standalone: true,
  template: '',
  styleUrl: '../../../styles/src/input/input.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'slotted-input',
    'data-slotted-component': 'input',
    'data-part': 'root',
    '[attr.data-size]': 'size()',
    '[attr.data-disabled]': "isDisabled() ? '' : null",
    '[attr.data-invalid]': "isInvalid() ? '' : null",
    '[attr.data-readonly]': "isReadOnly() ? '' : null",
    '[attr.id]': 'controlId()',
    '[attr.aria-describedby]': 'describedBy()',
    '[attr.aria-invalid]': "isInvalid() ? 'true' : null",
    '[attr.aria-required]': "isRequired() ? 'true' : null",
    '[attr.disabled]': "isDisabled() ? '' : null",
    '[attr.readonly]': "isReadOnly() ? '' : null",
  },
})
export class SlInput {
  readonly disabled = input<boolean | undefined>(undefined);
  readonly invalid = input<boolean | undefined>(undefined);
  readonly readOnly = input<boolean | undefined>(undefined);
  readonly required = input<boolean | undefined>(undefined);
  readonly size = input<InputSize>('md');

  private readonly field = inject(SlField, { optional: true });
  private readonly element = inject(ElementRef<HTMLElement>).nativeElement;

  private readonly own = {
    ariaDescribedBy: this.element.getAttribute('aria-describedby'),
    id: this.element.getAttribute('id'),
  };

  protected readonly isDisabled = computed(
    () => this.disabled() ?? this.field?.disabled() ?? false,
  );

  protected readonly isInvalid = computed(() => this.invalid() ?? this.field?.invalid() ?? false);

  protected readonly isReadOnly = computed(
    () => this.readOnly() ?? this.field?.readOnly() ?? false,
  );

  protected readonly isRequired = computed(
    () => this.required() ?? this.field?.required() ?? false,
  );

  protected readonly controlId = computed(() => this.own.id ?? this.field?.controlId() ?? null);

  protected readonly describedBy = computed(() => {
    const ids = [this.own.ariaDescribedBy, this.field?.describedBy()].filter(
      (value): value is string => value !== null && value !== undefined && value !== '',
    );
    return ids.length > 0 ? ids.join(' ') : null;
  });

  constructor() {
    this.field?.registerControl();
  }
}

// packages/react/src/input/input.tsx
import '@slotted/styles/input/input.css';

import { useEffect } from 'react';

import { useField } from '../field/field-context';
import type { InputProps } from './input.types';

function mergeDescribedBy(consumer: string | undefined, field: string | undefined) {
  return [consumer, field].filter(Boolean).join(' ') || undefined;
}

/**
 * The native control, wired to the field around it when there is one and
 * standing alone when there is not.
 *
 * Every shared state is undefined by default. Unset defers to the field; set
 * wins over it, in both directions. The resolved value is mirrored onto the
 * element as a data attribute, so the stylesheet is one selector and an input
 * outside a field looks the same as one inside it.
 */
export function Input({
  'aria-describedby': ariaDescribedBy,
  'aria-invalid': ariaInvalid,
  'aria-required': ariaRequired,
  className,
  disabled,
  id,
  invalid,
  readOnly,
  required,
  size = 'md',
  ...nativeProps
}: InputProps) {
  const field = useField();
  const registerControl = field?.registerControl;

  useEffect(() => registerControl?.(), [registerControl]);

  const isDisabled = disabled ?? field?.disabled ?? false;
  const isInvalid = invalid ?? field?.invalid ?? false;
  const isReadOnly = readOnly ?? field?.readOnly ?? false;
  const isRequired = required ?? field?.required ?? false;

  return (
    <input
      {...nativeProps}
      aria-describedby={mergeDescribedBy(ariaDescribedBy, field?.describedBy)}
      aria-invalid={ariaInvalid ?? (isInvalid ? true : undefined)}
      aria-required={ariaRequired ?? (isRequired ? true : undefined)}
      className={['slotted-input', className].filter(Boolean).join(' ')}
      data-disabled={isDisabled ? '' : undefined}
      data-invalid={isInvalid ? '' : undefined}
      data-part="root"
      data-readonly={isReadOnly ? '' : undefined}
      data-size={size}
      data-slotted-component="input"
      disabled={isDisabled}
      id={id ?? field?.ids.control}
      readOnly={isReadOnly}
    />
  );
}
