// packages/react/src/collapsible/collapsible.tsx
import '@slotted/styles/collapsible/collapsible.css';

import { useState } from 'react';
import type { SyntheticEvent } from 'react';

import type { CollapsibleProps } from './collapsible.types';

/**
 * A `details` element, so the expanded state, the keyboard model and the role
 * come from the platform. The component adds only the controlled-value shape
 * the rest of the library uses.
 */
export function Collapsible({
  className,
  defaultOpen = false,
  onOpenChange,
  open,
  ...nativeProps
}: CollapsibleProps) {
  const [uncontrolled, setUncontrolled] = useState(defaultOpen);
  const isOpen = open ?? uncontrolled;

  const handleToggle = (event: SyntheticEvent<HTMLDetailsElement>) => {
    const next = event.currentTarget.open;
    if (next === isOpen) return;

    if (open === undefined) {
      setUncontrolled(next);
    } else {
      /**
       * The element opened itself. A controlled collapsible may only be where
       * the consumer says it is, so it is put back at once; the reassignment
       * fires a second toggle, which the guard above discards. If the consumer
       * does accept the change, the new prop lands on the next render.
       */
      event.currentTarget.open = open;
    }

    onOpenChange?.(next);
  };

  return (
    <details
      {...nativeProps}
      className={['slotted-collapsible', className].filter(Boolean).join(' ')}
      data-part="root"
      data-slotted-component="collapsible"
      onToggle={handleToggle}
      open={isOpen}
    />
  );
}

// packages/angular/collapsible/src/collapsible.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  inject,
  model,
  ViewEncapsulation,
} from '@angular/core';

/**
 * A `details` element, so the expanded state, the keyboard model and the role
 * come from the platform. The component adds only the two-way value the rest
 * of the library uses.
 */
@Component({
  selector: 'details[slCollapsible]',
  standalone: true,
  template: '<ng-content></ng-content>',
  styleUrl: '../../../styles/src/collapsible/collapsible.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'slotted-collapsible',
    'data-slotted-component': 'collapsible',
    'data-part': 'root',
    '[attr.open]': "open() ? '' : null",
    '(toggle)': 'handleToggle()',
  },
})
export class SlCollapsible {
  readonly open = model(false);

  private readonly element = inject(ElementRef<HTMLDetailsElement>).nativeElement;

  handleToggle() {
    const next = this.element.open;
    if (next === this.open()) return;
    this.open.set(next);
  }
}
