// packages/angular/breadcrumb/src/breadcrumb.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  ViewEncapsulation,
} from '@angular/core';

/**
 * A nav needs a name: a page usually has more than one, and "navigation" twice
 * in a landmark list tells a reader nothing. The default names this one after
 * what it is, and steps aside when the consumer pointed at visible text.
 */
@Component({
  selector: 'nav[slBreadcrumb]',
  standalone: true,
  template: '<ng-content></ng-content>',
  styleUrl: '../../../styles/src/breadcrumb/breadcrumb.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'slotted-breadcrumb',
    'data-slotted-component': 'breadcrumb',
    'data-part': 'root',
    '[attr.aria-label]': 'ariaLabel()',
  },
})
export class SlBreadcrumb {
  private readonly element = inject(ElementRef<HTMLElement>).nativeElement;

  private readonly own = {
    ariaLabel: this.element.getAttribute('aria-label'),
    ariaLabelledBy: this.element.getAttribute('aria-labelledby'),
  };

  readonly ariaLabel = computed(() => {
    if (this.own.ariaLabelledBy !== null) return this.own.ariaLabel;
    return this.own.ariaLabel ?? 'Breadcrumb';
  });
}

// packages/react/src/breadcrumb/breadcrumb.tsx
import '@slotted/styles/breadcrumb/breadcrumb.css';

import type { BreadcrumbProps, BreadcrumbRootProps } from './breadcrumb.types';

/**
 * A nav needs a name: a page usually has more than one, and "navigation" twice
 * in a landmark list tells a reader nothing. The default names this one after
 * what it is, and a consumer with two breadcrumbs on a page replaces it.
 */
export function Breadcrumb({
  'aria-label': ariaLabel,
  'aria-labelledby': ariaLabelledBy,
  className,
  render,
  ...nativeProps
}: BreadcrumbProps) {
  const rootProps: BreadcrumbRootProps = {
    ...nativeProps,
    'aria-label': ariaLabelledBy === undefined ? (ariaLabel ?? 'Breadcrumb') : ariaLabel,
    'aria-labelledby': ariaLabelledBy,
    className: ['slotted-breadcrumb', className].filter(Boolean).join(' '),
    'data-part': 'root',
    'data-slotted-component': 'breadcrumb',
  };

  return render === undefined ? <nav {...rootProps} /> : render(rootProps);
}
