// packages/react/src/pagination/pagination-ellipsis.tsx
import type { PaginationEllipsisProps } from './pagination.types';

/**
 * Hidden from assistive technology: a gap between two page numbers is not a
 * destination, and reading "ellipsis" between four and nine helps nobody.
 */
export function PaginationEllipsis({
  'aria-hidden': ariaHidden,
  children,
  ...nativeProps
}: PaginationEllipsisProps) {
  return (
    <span {...nativeProps} aria-hidden={ariaHidden ?? 'true'} data-part="ellipsis">
      {children ?? '…'}
    </span>
  );
}

// packages/angular/pagination/src/pagination-ellipsis.ts
import { computed, Directive, ElementRef, inject } from '@angular/core';

/**
 * Hidden from assistive technology: a gap between two page numbers is not a
 * destination, and reading "ellipsis" between four and nine helps nobody.
 */
@Directive({
  selector: 'span[slPaginationEllipsis]',
  standalone: true,
  host: {
    'data-part': 'ellipsis',
    '[attr.aria-hidden]': 'ariaHidden()',
  },
})
export class SlPaginationEllipsis {
  private readonly ownAriaHidden = inject(ElementRef<HTMLElement>).nativeElement.getAttribute(
    'aria-hidden',
  );

  readonly ariaHidden = computed(() => this.ownAriaHidden ?? 'true');
}
