// packages/react/src/pagination/pagination-list.tsx
import type { PaginationListProps } from './pagination.types';

/**
 * An unordered list, where Breadcrumb uses an ordered one. The pages are
 * siblings a reader may visit in any order, and numbering them twice tells a
 * screen reader nothing it cannot already read on the controls.
 */
export function PaginationList(props: PaginationListProps) {
  return <ul {...props} data-part="list" />;
}

// packages/angular/pagination/src/pagination-list.ts
import { Directive } from '@angular/core';

/**
 * An unordered list, where Breadcrumb uses an ordered one. The pages are
 * siblings a reader may visit in any order, and numbering them twice tells a
 * screen reader nothing it cannot already read on the controls.
 */
@Directive({
  selector: 'ul[slPaginationList]',
  standalone: true,
  host: {
    'data-part': 'list',
  },
})
export class SlPaginationList {}
