// packages/react/src/textarea/textarea.tsx
import '@slotted/styles/textarea/textarea.css';

import { useEffect } from 'react';

import { useField } from '../field/field-context';
import type { TextareaProps } from './textarea.types';

function mergeDescribedBy(consumer: string | undefined, field: string | undefined) {
  return [consumer, field].filter(Boolean).join(' ') || undefined;
}

/**
 * The multi-line control, wired to the field around it when there is one and
 * standing alone when there is not. It follows the mechanism Input set: unset
 * defers to the field, set wins over it, and the resolved state is mirrored
 * onto the element.
 */
export function Textarea({
  'aria-describedby': ariaDescribedBy,
  'aria-invalid': ariaInvalid,
  'aria-required': ariaRequired,
  autoSize = false,
  className,
  disabled,
  id,
  invalid,
  readOnly,
  required,
  rows = 3,
  size = 'md',
  ...nativeProps
}: TextareaProps) {
  const field = useField();
  const registerControl = field?.registerControl;

  useEffect(() => registerControl?.(), [registerControl]);

  const isDisabled = disabled ?? field?.disabled ?? false;
  const isInvalid = invalid ?? field?.invalid ?? false;
  const isReadOnly = readOnly ?? field?.readOnly ?? false;
  const isRequired = required ?? field?.required ?? false;

  return (
    <textarea
      {...nativeProps}
      aria-describedby={mergeDescribedBy(ariaDescribedBy, field?.describedBy)}
      aria-invalid={ariaInvalid ?? (isInvalid ? true : undefined)}
      aria-required={ariaRequired ?? (isRequired ? true : undefined)}
      className={['slotted-textarea', className].filter(Boolean).join(' ')}
      data-auto-size={autoSize ? '' : undefined}
      data-disabled={isDisabled ? '' : undefined}
      data-invalid={isInvalid ? '' : undefined}
      data-part="root"
      data-readonly={isReadOnly ? '' : undefined}
      data-size={size}
      data-slotted-component="textarea"
      disabled={isDisabled}
      id={id ?? field?.ids.control}
      readOnly={isReadOnly}
      rows={rows}
    />
  );
}

// packages/angular/textarea/src/textarea.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  numberAttribute,
  ViewEncapsulation,
} from '@angular/core';
import { SlField } from '@slotted/angular/field';

export type TextareaSize = 'sm' | 'md' | 'lg';

/**
 * The multi-line control, wired to the field around it when there is one and
 * standing alone when there is not. It follows the mechanism SlInput set:
 * unset defers to the field, set wins over it, and the resolved state is
 * mirrored onto the element.
 */
@Component({
  selector: 'textarea[slTextarea]',
  standalone: true,
  template: '',
  styleUrl: '../../../styles/src/textarea/textarea.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'slotted-textarea',
    'data-slotted-component': 'textarea',
    'data-part': 'root',
    '[attr.data-size]': 'size()',
    '[attr.data-auto-size]': "autoSize() ? '' : null",
    '[attr.data-disabled]': "isDisabled() ? '' : null",
    '[attr.data-invalid]': "isInvalid() ? '' : null",
    '[attr.data-readonly]': "isReadOnly() ? '' : null",
    '[attr.rows]': 'rows()',
    '[attr.id]': 'controlId()',
    '[attr.aria-describedby]': 'describedBy()',
    '[attr.aria-invalid]': "isInvalid() ? 'true' : null",
    '[attr.aria-required]': "isRequired() ? 'true' : null",
    '[attr.disabled]': "isDisabled() ? '' : null",
    '[attr.readonly]': "isReadOnly() ? '' : null",
  },
})
export class SlTextarea {
  readonly autoSize = input(false, { transform: booleanAttribute });
  readonly disabled = input<boolean | undefined>(undefined);
  readonly invalid = input<boolean | undefined>(undefined);
  readonly readOnly = input<boolean | undefined>(undefined);
  readonly required = input<boolean | undefined>(undefined);
  readonly rows = input(3, { transform: numberAttribute });
  readonly size = input<TextareaSize>('md');

  private readonly field = inject(SlField, { optional: true });
  private readonly element = inject(ElementRef<HTMLElement>).nativeElement;

  private readonly own = {
    ariaDescribedBy: this.element.getAttribute('aria-describedby'),
    id: this.element.getAttribute('id'),
  };

  protected readonly isDisabled = computed(
    () => this.disabled() ?? this.field?.disabled() ?? false,
  );

  protected readonly isInvalid = computed(() => this.invalid() ?? this.field?.invalid() ?? false);

  protected readonly isReadOnly = computed(
    () => this.readOnly() ?? this.field?.readOnly() ?? false,
  );

  protected readonly isRequired = computed(
    () => this.required() ?? this.field?.required() ?? false,
  );

  protected readonly controlId = computed(() => this.own.id ?? this.field?.controlId() ?? null);

  protected readonly describedBy = computed(() => {
    const ids = [this.own.ariaDescribedBy, this.field?.describedBy()].filter(
      (value): value is string => value !== null && value !== undefined && value !== '',
    );
    return ids.length > 0 ? ids.join(' ') : null;
  });

  constructor() {
    this.field?.registerControl();
  }
}
