// packages/react/src/tabs/tab.tsx
import { tabsClassName, useTabs } from './tabs-context';
import type { TabProps } from './tabs.types';

export function Tab({
  className,
  disabled = false,
  onClick,
  onKeyDown,
  value,
  ...nativeProps
}: TabProps) {
  const { activation, panelId, select, tabId, value: selected } = useTabs();
  const isSelected = selected === value;

  return (
    <button
      {...nativeProps}
      aria-controls={panelId(value)}
      aria-selected={isSelected}
      className={tabsClassName('slotted-tabs__tab', className)}
      data-disabled={disabled ? '' : undefined}
      data-part="tab"
      data-selected={isSelected ? '' : undefined}
      data-value={value}
      disabled={disabled}
      id={tabId(value)}
      onClick={(event) => {
        onClick?.(event);
        if (!event.defaultPrevented) select(value);
      }}
      onKeyDown={(event) => {
        onKeyDown?.(event);
        if (event.defaultPrevented || activation !== 'manual') return;
        if (event.key === 'Enter' || event.key === ' ') {
          event.preventDefault();
          select(value);
        }
      }}
      role="tab"
      type="button"
    />
  );
}

// packages/angular/tabs/src/tab.ts
import { booleanAttribute, computed, Directive, inject, input } from '@angular/core';

import { SlTabs } from './tabs';

@Directive({
  selector: 'button[slTab]',
  standalone: true,
  host: {
    'data-part': 'tab',
    role: 'tab',
    type: 'button',
    '[attr.id]': 'tabs.tabId(value())',
    '[attr.data-value]': 'value()',
    '[attr.aria-controls]': 'tabs.panelId(value())',
    '[attr.aria-selected]': 'selected()',
    '[attr.data-selected]': "selected() ? '' : null",
    '[attr.data-disabled]': "disabled() ? '' : null",
    '[disabled]': 'disabled()',
    '(click)': 'select()',
    '(keydown)': 'handleKeydown($event)',
  },
})
export class SlTab {
  readonly value = input.required<string>();
  readonly disabled = input(false, { transform: booleanAttribute });

  protected readonly tabs = inject(SlTabs);

  readonly selected = computed(() => this.tabs.value() === this.value());

  select() {
    if (this.disabled()) return;
    this.tabs.select(this.value());
  }

  handleKeydown(event: KeyboardEvent) {
    if (this.tabs.activation() !== 'manual') return;
    if (event.key !== 'Enter' && event.key !== ' ') return;
    event.preventDefault();
    this.select();
  }
}
