// packages/angular/field/src/field-control.ts
import { computed, Directive, ElementRef, inject } from '@angular/core';

import { SlField } from './field';

/**
 * Applies the field's wiring to any control, including a plain native input.
 * Every binding yields to a value the consumer already placed on the element,
 * which is the family's invariant: the field fills what is unset and never
 * overwrites what was passed.
 */
@Directive({
  selector: '[slFieldControl]',
  standalone: true,
  host: {
    'data-part': 'control',
    '[attr.id]': 'id()',
    '[attr.aria-describedby]': 'describedBy()',
    '[attr.aria-invalid]': 'ariaInvalid()',
    '[attr.aria-required]': 'ariaRequired()',
    '[attr.disabled]': 'disabled()',
    '[attr.readonly]': 'readOnly()',
  },
})
export class SlFieldControl {
  private readonly field = inject(SlField);
  private readonly element = inject(ElementRef<HTMLElement>).nativeElement;

  private readonly own = {
    ariaDescribedBy: this.element.getAttribute('aria-describedby'),
    ariaInvalid: this.element.getAttribute('aria-invalid'),
    ariaRequired: this.element.getAttribute('aria-required'),
    disabled: this.element.getAttribute('disabled'),
    id: this.element.getAttribute('id'),
    readOnly: this.element.getAttribute('readonly'),
  };

  readonly id = computed(() => this.own.id ?? this.field.controlId());

  readonly describedBy = computed(() => {
    const ids = [this.own.ariaDescribedBy, this.field.describedBy()].filter(
      (value): value is string => value !== null && value !== '',
    );
    return ids.length > 0 ? ids.join(' ') : null;
  });

  readonly ariaInvalid = computed(
    () => this.own.ariaInvalid ?? (this.field.invalid() ? 'true' : null),
  );

  readonly ariaRequired = computed(
    () => this.own.ariaRequired ?? (this.field.required() ? 'true' : null),
  );

  readonly disabled = computed(() => this.own.disabled ?? (this.field.disabled() ? '' : null));

  readonly readOnly = computed(() => this.own.readOnly ?? (this.field.readOnly() ? '' : null));

  constructor() {
    this.field.registerControl();
  }
}

// packages/react/src/field/field-control.tsx
import { useEffect } from 'react';

import { useField } from './field-context';
import type { FieldControlProps, FieldControlRootProps } from './field.types';

function mergeDescribedBy(consumer: string | undefined, field: string | undefined) {
  return [consumer, field].filter(Boolean).join(' ') || undefined;
}

export function FieldControl({
  'aria-describedby': ariaDescribedBy,
  'aria-invalid': ariaInvalid,
  'aria-required': ariaRequired,
  disabled,
  id,
  readOnly,
  render,
  ...nativeProps
}: FieldControlProps) {
  const field = useField();
  const registerControl = field?.registerControl;

  useEffect(() => registerControl?.(), [registerControl]);

  const rootProps: FieldControlRootProps = {
    ...nativeProps,
    'aria-describedby': mergeDescribedBy(ariaDescribedBy, field?.describedBy),
    'aria-invalid': ariaInvalid ?? (field?.invalid ? true : undefined),
    'aria-required': ariaRequired ?? (field?.required ? true : undefined),
    'data-part': 'control',
    disabled: disabled ?? field?.disabled,
    id: id ?? field?.ids.control,
    readOnly: readOnly ?? field?.readOnly,
  };

  return render === undefined ? <input {...rootProps} /> : render(rootProps);
}
