// packages/angular/field/src/field.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  isDevMode,
  signal,
  ViewEncapsulation,
} from '@angular/core';

import { SlFieldIdFactory } from './field-id';

@Component({
  selector: 'div[slField]',
  standalone: true,
  template: '<ng-content></ng-content>',
  styleUrl: '../../../styles/src/field/field.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'slotted-field',
    'data-slotted-component': 'field',
    'data-part': 'root',
    '[attr.data-disabled]': "disabled() ? '' : null",
    '[attr.data-invalid]': "invalid() ? '' : null",
    '[attr.data-readonly]': "readOnly() ? '' : null",
    '[attr.data-required]': "required() ? '' : null",
  },
})
export class SlField {
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly invalid = input(false, { transform: booleanAttribute });
  readonly readOnly = input(false, { transform: booleanAttribute });
  readonly required = input(false, { transform: booleanAttribute });
  readonly fieldId = input<string | null>(null, { alias: 'id' });

  private readonly generatedId = inject(SlFieldIdFactory).next();
  private readonly parts = signal<readonly ('description' | 'error')[]>([]);
  private hasControl = false;

  readonly base = computed(() => this.fieldId() ?? this.generatedId);
  readonly controlId = computed(() => `${this.base()}-control`);
  readonly labelId = computed(() => `${this.base()}-label`);
  readonly descriptionId = computed(() => `${this.base()}-description`);
  readonly errorId = computed(() => `${this.base()}-error`);

  readonly describedBy = computed(() => {
    const parts = this.parts();
    const ids = [
      parts.includes('description') ? this.descriptionId() : null,
      parts.includes('error') ? this.errorId() : null,
    ].filter((id): id is string => id !== null);
    return ids.length > 0 ? ids.join(' ') : null;
  });

  registerPart(part: 'description' | 'error') {
    this.parts.update((current) => (current.includes(part) ? current : [...current, part]));
  }

  releasePart(part: 'description' | 'error') {
    this.parts.update((current) => current.filter((candidate) => candidate !== part));
  }

  registerControl() {
    this.hasControl = true;
  }

  ngAfterViewInit() {
    if (!isDevMode() || this.hasControl) return;
    console.warn(
      'Field rendered without a control. Add slFieldControl to the control, or use a control that reads the field, so the label resolves.',
    );
  }
}

// packages/react/src/field/field.tsx
import '@slotted/styles/field/field.css';

import { useCallback, useEffect, useId, useMemo, useRef, useState } from 'react';

import { deriveIds, FieldContext, fieldClassName } from './field-context';
import type { FieldContextValue, FieldProps } from './field.types';

const isDevelopment = (import.meta as ImportMeta & { env?: { DEV?: boolean } }).env?.DEV === true;

export function Field({
  children,
  className,
  disabled = false,
  id,
  invalid = false,
  readOnly = false,
  render,
  required = false,
  ...nativeProps
}: FieldProps) {
  const generatedId = useId();
  const ids = useMemo(() => deriveIds(id ?? `slotted-field-${generatedId}`), [generatedId, id]);

  const [parts, setParts] = useState<readonly ('description' | 'error')[]>([]);
  const hasControl = useRef(false);

  const registerPart = useCallback((part: 'description' | 'error') => {
    setParts((current) => (current.includes(part) ? current : [...current, part]));
    return () => setParts((current) => current.filter((candidate) => candidate !== part));
  }, []);

  const registerControl = useCallback(() => {
    hasControl.current = true;
  }, []);

  useEffect(() => {
    if (!isDevelopment || hasControl.current) return;
    console.warn(
      'Field rendered without a control. Wrap the control in FieldControl, or use a control that reads the field, so the label resolves.',
    );
  }, []);

  const describedBy =
    [
      parts.includes('description') ? ids.description : undefined,
      parts.includes('error') ? ids.error : undefined,
    ]
      .filter(Boolean)
      .join(' ') || undefined;

  const value: FieldContextValue = {
    describedBy,
    disabled,
    ids,
    invalid,
    readOnly,
    registerControl,
    registerPart,
    required,
  };

  const rootProps = {
    ...nativeProps,
    children,
    className: fieldClassName(className),
    'data-disabled': disabled ? '' : undefined,
    'data-invalid': invalid ? '' : undefined,
    'data-part': 'root',
    'data-readonly': readOnly ? '' : undefined,
    'data-required': required ? '' : undefined,
    'data-slotted-component': 'field',
  } as const;

  return (
    <FieldContext.Provider value={value}>
      {render === undefined ? <div {...rootProps} /> : render(rootProps)}
    </FieldContext.Provider>
  );
}
