// packages/react/src/loading-bar/loading-bar.tsx
import '@slotted/styles/loading-bar/loading-bar.css';

import { clamp, percentOf } from '@slotted/core/measure';

import type { LoadingBarProps, LoadingBarRootProps } from './loading-bar.types';

const isDevelopment = (import.meta as ImportMeta & { env?: { DEV?: boolean } }).env?.DEV === true;

/**
 * The same measurement as ProgressBar, reported the same way. What differs is
 * where it sits: a page-level bar belongs to the viewport, not to whatever
 * happens to contain it.
 */
export function LoadingBar({
  'aria-label': ariaLabel,
  'aria-labelledby': ariaLabelledBy,
  className,
  max = 100,
  placement = 'inline',
  render,
  value = null,
  valueText,
  ...nativeProps
}: LoadingBarProps) {
  if (isDevelopment && !ariaLabel?.trim() && !ariaLabelledBy?.trim()) {
    console.warn(
      'LoadingBar has no accessible name. Give it aria-label, or aria-labelledby pointing at the text that names it.',
    );
  }

  const indeterminate = value === null || Number.isNaN(value);
  const clamped = indeterminate ? 0 : clamp(value, 0, max);

  const rootProps: LoadingBarRootProps = {
    ...nativeProps,
    'aria-label': ariaLabel,
    'aria-labelledby': ariaLabelledBy,
    'aria-valuemax': max,
    'aria-valuemin': 0,
    'aria-valuenow': indeterminate ? undefined : clamped,
    'aria-valuetext': valueText,
    children: (
      <span
        data-part="indicator"
        style={indeterminate ? undefined : { inlineSize: `${percentOf(clamped, 0, max)}%` }}
      />
    ),
    className: ['slotted-loading-bar', className].filter(Boolean).join(' '),
    'data-indeterminate': indeterminate ? '' : undefined,
    'data-part': 'root',
    'data-placement': placement,
    'data-slotted-component': 'loading-bar',
    role: 'progressbar',
  };

  return render === undefined ? <div {...rootProps} /> : render(rootProps);
}

// packages/angular/loading-bar/src/loading-bar.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  isDevMode,
  ViewEncapsulation,
} from '@angular/core';
import { clamp, percentOf } from '@slotted/core/measure';

export type LoadingBarPlacement = 'inline' | 'fixed';

/**
 * The same measurement as ProgressBar, reported the same way. What differs is
 * where it sits: a page-level bar belongs to the viewport, not to whatever
 * happens to contain it.
 */
@Component({
  selector: 'div[slLoadingBar]',
  standalone: true,
  template: `<span data-part="indicator" [style.inline-size]="indicatorSize()"></span>`,
  styleUrl: '../../../styles/src/loading-bar/loading-bar.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'slotted-loading-bar',
    'data-slotted-component': 'loading-bar',
    'data-part': 'root',
    role: 'progressbar',
    'aria-valuemin': '0',
    '[attr.aria-valuemax]': 'max()',
    '[attr.aria-valuenow]': 'valueNow()',
    '[attr.aria-valuetext]': 'valueText() || null',
    '[attr.data-placement]': 'placement()',
    '[attr.data-indeterminate]': "indeterminate() ? '' : null",
  },
})
export class SlLoadingBar {
  readonly max = input(100);
  readonly placement = input<LoadingBarPlacement>('inline');
  readonly value = input<number | null>(null);
  readonly valueText = input('');

  private readonly element = inject(ElementRef<HTMLElement>).nativeElement;

  readonly indeterminate = computed(() => {
    const value = this.value();
    return value === null || Number.isNaN(value);
  });

  readonly valueNow = computed(() =>
    this.indeterminate() ? null : clamp(this.value() as number, 0, this.max()),
  );

  readonly indicatorSize = computed(() => {
    const now = this.valueNow();
    return now === null ? null : `${percentOf(now, 0, this.max())}%`;
  });

  constructor() {
    if (!isDevMode()) return;
    const ariaLabel = this.element.getAttribute('aria-label');
    const ariaLabelledBy = this.element.getAttribute('aria-labelledby');
    if (!ariaLabel?.trim() && !ariaLabelledBy?.trim()) {
      console.warn(
        'LoadingBar has no accessible name. Give it aria-label, or aria-labelledby pointing at the text that names it.',
      );
    }
  }
}
