// packages/angular/pagination/src/pagination.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  ViewEncapsulation,
} from '@angular/core';

/**
 * A nav needs a name, and a page with a pagination control usually has other
 * navigation on it. The default names this one; an aria-labelledby already on
 * the element suppresses it, so the two never both appear.
 */
@Component({
  selector: 'nav[slPagination]',
  standalone: true,
  template: '<ng-content></ng-content>',
  styleUrl: '../../../styles/src/pagination/pagination.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'slotted-pagination',
    'data-slotted-component': 'pagination',
    'data-part': 'root',
    '[attr.aria-label]': 'ariaLabel()',
  },
})
export class SlPagination {
  private readonly element = inject(ElementRef<HTMLElement>).nativeElement;

  private readonly own = {
    ariaLabel: this.element.getAttribute('aria-label'),
    ariaLabelledBy: this.element.getAttribute('aria-labelledby'),
  };

  readonly ariaLabel = computed(() =>
    this.own.ariaLabelledBy !== null ? this.own.ariaLabel : (this.own.ariaLabel ?? 'Pagination'),
  );
}

// packages/react/src/pagination/pagination.tsx
import '@slotted/styles/pagination/pagination.css';

import type { PaginationProps, PaginationRootProps } from './pagination.types';

/**
 * A nav needs a name, and a page with a pagination control usually has other
 * navigation on it. The default names this one; a consumer pointing at visible
 * text with aria-labelledby suppresses it, so the two never both appear.
 */
export function Pagination({
  'aria-label': ariaLabel,
  'aria-labelledby': ariaLabelledBy,
  className,
  render,
  ...nativeProps
}: PaginationProps) {
  const rootProps: PaginationRootProps = {
    ...nativeProps,
    'aria-label': ariaLabelledBy === undefined ? (ariaLabel ?? 'Pagination') : ariaLabel,
    'aria-labelledby': ariaLabelledBy,
    className: ['slotted-pagination', className].filter(Boolean).join(' '),
    'data-part': 'root',
    'data-slotted-component': 'pagination',
  };

  return render === undefined ? <nav {...rootProps} /> : render(rootProps);
}
