// packages/angular/splitter/src/splitter.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  model,
  numberAttribute,
  ViewEncapsulation,
} from '@angular/core';
import { clamp, roundTo } from '@slotted/core/measure';

export type SplitterOrientation = 'horizontal' | 'vertical';

export function clampPosition(value: number, min: number, max: number) {
  return roundTo(clamp(value, min, max), 2);
}

/**
 * The position is the first grid track's size, written as a style binding on
 * the root. A percentage rather than a pixel count, because the container is
 * not measured until layout and a pixel position taken from one viewport is
 * wrong on the next.
 */
@Component({
  selector: 'div[slSplitter]',
  standalone: true,
  template: '<ng-content></ng-content>',
  styleUrl: '../../../styles/src/splitter/splitter.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'slotted-splitter',
    'data-slotted-component': 'splitter',
    'data-part': 'root',
    '[attr.data-orientation]': 'orientation()',
    '[style.grid-template-columns]': 'columns()',
    '[style.grid-template-rows]': 'rows()',
  },
})
export class SlSplitter {
  readonly max = input(100, { transform: numberAttribute });
  readonly min = input(0, { transform: numberAttribute });
  readonly orientation = input<SplitterOrientation>('horizontal');
  readonly step = input(5, { transform: numberAttribute });
  readonly value = model(50);

  readonly element = inject(ElementRef<HTMLElement>).nativeElement;

  private restore = 50;

  readonly position = computed(() => clampPosition(this.value(), this.min(), this.max()));

  private readonly track = computed(() => `${this.position()}% auto 1fr`);

  readonly columns = computed(() => (this.orientation() === 'horizontal' ? this.track() : null));

  readonly rows = computed(() => (this.orientation() === 'vertical' ? this.track() : null));

  setValue(next: number) {
    this.value.set(clampPosition(next, this.min(), this.max()));
  }

  toggleCollapse() {
    const position = this.position();
    const min = this.min();
    if (position > min) {
      this.restore = position;
      this.setValue(min);
      return;
    }
    this.setValue(this.restore > min ? this.restore : this.max());
  }
}

// packages/react/src/splitter/splitter.tsx
import '@slotted/styles/splitter/splitter.css';

import { useCallback, useMemo, useRef, useState } from 'react';

import { clampPosition, SplitterContext } from './splitter-context';
import type { SplitterContextValue, SplitterProps } from './splitter.types';

/**
 * The position is the first grid track's size, written inline. A percentage
 * rather than a pixel count, because the container is not measured until
 * layout and a pixel position taken from one viewport is wrong on the next.
 */
export function Splitter({
  children,
  className,
  defaultValue = 50,
  max = 100,
  min = 0,
  onValueChange,
  orientation = 'horizontal',
  step = 5,
  style,
  value,
  ...nativeProps
}: SplitterProps) {
  const rootRef = useRef<HTMLDivElement>(null);
  const restore = useRef(clampPosition(value ?? defaultValue, min, max));
  const [uncontrolled, setUncontrolled] = useState(defaultValue);
  const position = clampPosition(value ?? uncontrolled, min, max);

  const setValue = useCallback(
    (next: number) => {
      const clamped = clampPosition(next, min, max);
      if (value === undefined) setUncontrolled(clamped);
      onValueChange?.(clamped);
    },
    [max, min, onValueChange, value],
  );

  const toggleCollapse = useCallback(() => {
    if (position > min) {
      restore.current = position;
      setValue(min);
      return;
    }
    setValue(restore.current > min ? restore.current : max);
  }, [max, min, position, setValue]);

  const context = useMemo<SplitterContextValue>(
    () => ({ max, min, orientation, rootRef, setValue, step, toggleCollapse, value: position }),
    [max, min, orientation, position, setValue, step, toggleCollapse],
  );

  const track = `${position}% auto 1fr`;

  return (
    <SplitterContext.Provider value={context}>
      <div
        {...nativeProps}
        className={['slotted-splitter', className].filter(Boolean).join(' ')}
        data-orientation={orientation}
        data-part="root"
        data-slotted-component="splitter"
        ref={rootRef}
        style={{
          ...style,
          ...(orientation === 'horizontal'
            ? { gridTemplateColumns: track }
            : { gridTemplateRows: track }),
        }}
      >
        {children}
      </div>
    </SplitterContext.Provider>
  );
}
