// packages/react/src/link/link.tsx
import '@slotted/styles/link/link.css';
import '@slotted/styles/visually-hidden/visually-hidden.css';

import type { LinkProps, LinkRootProps } from './link.types';

/**
 * `external` sets the two attributes a new-tab link needs and appends the
 * warning it owes the reader. Every one of them yields to a value the consumer
 * passed: a link that opens in a named frame is still external, and the hint is
 * still the honest thing to say.
 *
 * The hint carries a leading space of its own. Name computation concatenates
 * adjacent text without inserting one, and "Documentation(opens in a new tab)"
 * is what a screen reader would then read out.
 */
export function Link({
  children,
  className,
  external = false,
  externalHint = '(opens in a new tab)',
  render,
  rel,
  target,
  underline = 'always',
  ...nativeProps
}: LinkProps) {
  const rootProps: LinkRootProps = {
    ...nativeProps,
    children: (
      <>
        {children}
        {external ? (
          <span className="slotted-visually-hidden" data-part="external-hint">
            {` ${externalHint}`}
          </span>
        ) : null}
      </>
    ),
    className: ['slotted-link', className].filter(Boolean).join(' '),
    'data-part': 'root',
    'data-slotted-component': 'link',
    'data-underline': underline,
    rel: rel ?? (external ? 'noopener noreferrer' : undefined),
    target: target ?? (external ? '_blank' : undefined),
  };

  return render === undefined ? <a {...rootProps} /> : render(rootProps);
}

// packages/angular/link/src/link.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  ViewEncapsulation,
} from '@angular/core';

export type LinkUnderline = 'always' | 'hover' | 'none';

/**
 * The hint carries a leading space inside the interpolated string rather than
 * in the template. Accessible name computation concatenates adjacent
 * alternatives without inserting one, and Angular strips a template's own
 * whitespace-only text node.
 */
@Component({
  selector: 'a[slLink]',
  standalone: true,
  template: `
    <ng-content></ng-content>
    @if (external()) {
      <span class="slotted-visually-hidden" data-part="external-hint">{{ hint() }}</span>
    }
  `,
  styleUrls: [
    '../../../styles/src/link/link.css',
    '../../../styles/src/visually-hidden/visually-hidden.css',
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'slotted-link',
    'data-slotted-component': 'link',
    'data-part': 'root',
    '[attr.data-underline]': 'underline()',
    '[attr.rel]': 'rel()',
    '[attr.target]': 'target()',
  },
})
export class SlLink {
  readonly external = input(false, { transform: booleanAttribute });
  readonly externalHint = input('(opens in a new tab)');
  readonly underline = input<LinkUnderline>('always');

  private readonly element = inject(ElementRef<HTMLElement>).nativeElement;
  private readonly own = {
    rel: this.element.getAttribute('rel'),
    target: this.element.getAttribute('target'),
  };

  readonly hint = computed(() => ` ${this.externalHint()}`);
  readonly rel = computed(() => this.own.rel ?? (this.external() ? 'noopener noreferrer' : null));
  readonly target = computed(() => this.own.target ?? (this.external() ? '_blank' : null));
}
