// packages/angular/avatar/src/avatar-fallback.ts
import { Directive } from '@angular/core';

/**
 * Always in the template. The stylesheet takes it out of the document once the
 * picture arrives, so the decision lives in one place and matches React.
 */
@Directive({
  selector: 'span[slAvatarFallback]',
  standalone: true,
  host: {
    'data-part': 'fallback',
  },
})
export class SlAvatarFallback {}

// packages/react/src/avatar/avatar-fallback.tsx
import type { AvatarFallbackProps } from './avatar.types';

/**
 * Always rendered. The stylesheet takes it out of the document once the
 * picture arrives, which keeps the two frameworks identical here and means the
 * fallback is present for the request that never returns.
 */
export function AvatarFallback(props: AvatarFallbackProps) {
  return <span {...props} data-part="fallback" />;
}
