// packages/angular/tabs/src/tab-panel.ts
import { computed, Directive, inject, input } from '@angular/core';

import { SlTabs } from './tabs';

@Directive({
  selector: 'div[slTabPanel]',
  standalone: true,
  host: {
    'data-part': 'panel',
    role: 'tabpanel',
    '[attr.id]': 'tabs.panelId(value())',
    '[attr.aria-labelledby]': 'tabs.tabId(value())',
    '[attr.hidden]': "selected() ? null : ''",
    '[attr.tabindex]': "selected() ? '0' : null",
  },
})
export class SlTabPanel {
  readonly value = input.required<string>();

  protected readonly tabs = inject(SlTabs);

  readonly selected = computed(() => this.tabs.value() === this.value());
}

// packages/react/src/tabs/tab-panel.tsx
import { tabsClassName, useTabs } from './tabs-context';
import type { TabPanelProps } from './tabs.types';

export function TabPanel({ className, value, ...nativeProps }: TabPanelProps) {
  const { panelId, tabId, value: selected } = useTabs();
  const isSelected = selected === value;

  return (
    <div
      {...nativeProps}
      aria-labelledby={tabId(value)}
      className={tabsClassName('slotted-tabs__panel', className)}
      data-part="panel"
      hidden={!isSelected}
      id={panelId(value)}
      role="tabpanel"
      tabIndex={isSelected ? 0 : undefined}
    />
  );
}
