// packages/angular/tabs/src/tabs.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  model,
  ViewEncapsulation,
} from '@angular/core';

import { SlTabsIdFactory } from './tabs-id';
import type { TabsActivation, TabsOrientation } from './tabs.constants';

@Component({
  selector: 'div[slTabs]',
  standalone: true,
  template: '<ng-content></ng-content>',
  styleUrl: '../../../styles/src/tabs/tabs.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'slotted-tabs',
    'data-slotted-component': 'tabs',
    'data-part': 'root',
    '[attr.data-orientation]': 'orientation()',
  },
})
export class SlTabs {
  readonly activation = input<TabsActivation>('automatic');
  readonly orientation = input<TabsOrientation>('horizontal');
  readonly value = model<string | undefined>(undefined);
  readonly tabsId = input<string | null>(null, { alias: 'id' });

  private readonly generatedId = inject(SlTabsIdFactory).next();

  readonly base = computed(() => this.tabsId() ?? this.generatedId);

  tabId(value: string) {
    return `${this.base()}-tab-${value}`;
  }

  panelId(value: string) {
    return `${this.base()}-panel-${value}`;
  }

  select(value: string) {
    this.value.set(value);
  }
}

// packages/react/src/tabs/tabs.tsx
import '@slotted/styles/tabs/tabs.css';

import { useCallback, useId, useMemo, useState } from 'react';

import { TabsContext, tabsClassName } from './tabs-context';
import type { TabsContextValue, TabsProps } from './tabs.types';

export function Tabs({
  activation = 'automatic',
  children,
  className,
  defaultValue,
  id,
  onValueChange,
  orientation = 'horizontal',
  value,
  ...nativeProps
}: TabsProps) {
  const generatedId = useId();
  const base = id ?? `slotted-tabs-${generatedId}`;
  const [uncontrolled, setUncontrolled] = useState(defaultValue);
  const selected = value ?? uncontrolled;

  const select = useCallback(
    (next: string) => {
      if (value === undefined) setUncontrolled(next);
      onValueChange?.(next);
    },
    [onValueChange, value],
  );

  const context = useMemo<TabsContextValue>(
    () => ({
      activation,
      orientation,
      panelId: (item) => `${base}-panel-${item}`,
      select,
      tabId: (item) => `${base}-tab-${item}`,
      value: selected,
    }),
    [activation, base, orientation, select, selected],
  );

  return (
    <TabsContext.Provider value={context}>
      <div
        {...nativeProps}
        className={tabsClassName('slotted-tabs', className)}
        data-orientation={orientation}
        data-part="root"
        data-slotted-component="tabs"
      >
        {children}
      </div>
    </TabsContext.Provider>
  );
}
