// packages/angular/description-list/src/description-list.ts
import { ChangeDetectionStrategy, Component, input, ViewEncapsulation } from '@angular/core';

export type DescriptionListOrientation = 'horizontal' | 'vertical';

@Component({
  selector: 'dl[slDescriptionList]',
  standalone: true,
  template: '<ng-content></ng-content>',
  styleUrl: '../../../styles/src/description-list/description-list.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'slotted-description-list',
    'data-slotted-component': 'description-list',
    'data-part': 'root',
    '[attr.data-orientation]': 'orientation()',
  },
})
export class SlDescriptionList {
  readonly orientation = input<DescriptionListOrientation>('vertical');
}

// packages/react/src/description-list/description-list.tsx
import '@slotted/styles/description-list/description-list.css';

import type { DescriptionListProps, DescriptionListRootProps } from './description-list.types';

export function DescriptionList({
  className,
  orientation = 'vertical',
  render,
  ...nativeProps
}: DescriptionListProps) {
  const rootProps: DescriptionListRootProps = {
    ...nativeProps,
    className: ['slotted-description-list', className].filter(Boolean).join(' '),
    'data-orientation': orientation,
    'data-part': 'root',
    'data-slotted-component': 'description-list',
  };

  return render === undefined ? <dl {...rootProps} /> : render(rootProps);
}
