// packages/angular/description-list/src/description-details.ts
import { Directive } from '@angular/core';

/**
 * A term may be followed by several of these. The stylesheet pins them to one
 * column so they stay under their term rather than displacing the next one.
 */
@Directive({
  selector: 'dd[slDescriptionDetails]',
  standalone: true,
  host: {
    'data-part': 'details',
  },
})
export class SlDescriptionDetails {}

// packages/react/src/description-list/description-details.tsx
import type { DescriptionDetailsProps } from './description-list.types';

/**
 * A term may be followed by several of these. The stylesheet pins them to one
 * column so they stay under their term rather than displacing the next one.
 */
export function DescriptionDetails(props: DescriptionDetailsProps) {
  return <dd {...props} data-part="details" />;
}
