// packages/angular/tag/src/tag.ts
import { ChangeDetectionStrategy, Component, input, ViewEncapsulation } from '@angular/core';

export type TagVariant = 'accent' | 'secondary' | 'success' | 'warning' | 'danger';
export type TagFill = 'solid' | 'outline' | 'subtle';
export type TagSize = 'sm' | 'md';

/**
 * The same three appearance axes as Badge, over the same five tones. A tag
 * differs from a badge in what the reader can do with it, not in how it looks.
 */
@Component({
  selector: 'span[slTag]',
  standalone: true,
  template: '<ng-content></ng-content>',
  styleUrl: '../../../styles/src/tag/tag.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'slotted-tag',
    'data-slotted-component': 'tag',
    'data-part': 'root',
    '[attr.data-variant]': 'variant()',
    '[attr.data-fill]': 'fill()',
    '[attr.data-size]': 'size()',
  },
})
export class SlTag {
  readonly fill = input<TagFill>('solid');
  readonly size = input<TagSize>('md');
  readonly variant = input<TagVariant>('secondary');
}

// packages/react/src/tag/tag.tsx
import '@slotted/styles/tag/tag.css';

import type { TagProps, TagRootProps } from './tag.types';

/**
 * The same three appearance axes as Badge, over the same five tones. A tag
 * differs from a badge in what the reader can do with it, not in how it looks.
 */
export function Tag({
  className,
  fill = 'solid',
  render,
  size = 'md',
  variant = 'secondary',
  ...nativeProps
}: TagProps) {
  const rootProps: TagRootProps = {
    ...nativeProps,
    className: ['slotted-tag', className].filter(Boolean).join(' '),
    'data-fill': fill,
    'data-part': 'root',
    'data-size': size,
    'data-slotted-component': 'tag',
    'data-variant': variant,
  };

  return render === undefined ? <span {...rootProps} /> : render(rootProps);
}
